[theme]
base = "light"
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"
font = "sans serif"

[theme.dark]
base = "dark"
primaryColor = "#58a6ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#eaecee"
font = "sans serif"

